services:
  alutec-inventory-be:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@alutec-inventory-postgres-db:5432/alutec-inventory-db?sslmode=disable
    depends_on:
      alutec-inventory-postgres-db:
        condition: service_healthy
    networks:
      - alutec-inventory-network

  alutec-inventory-postgres-db:
    image: postgres:14-alpine
    ports:
      - "54324:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alutec-inventory-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - alutec-inventory-network

networks:
  alutec-inventory-network:
    driver: bridge
